### ISSUE TITLE
Как растянуть яндекс карту на 100%?

### ISSUE THREAD

**Issue by SlimSavernake** [mihaylichenko/yii2-widget-mappicker#2]
ой простите. я как всегда настройки не заметил :)

Добавьте, пожалуйста, кнопку выбора спутника

**Comment by mihaylichenko** [comment]
Вы о какой кнопке? Выбор подложки карты?

**Comment by SlimSavernake** [comment]
ну да. возможность выбора пользователем спутника или схемы. а то в моей местности много домов на схеме не нарисовано.

**Comment by mihaylichenko** [comment]
Ок, принято, добавлю.
